# vim: et

on:
  workflow_call:

jobs:
  tests:
    name: Run Tox & PyTest
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python:
          - "3.11"
          - "3.12"
          - "3.13"

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065
        with:
          python-version: ${{ matrix.python }}

      - name: Prepare pip
        run: |
          python -m pip install --upgrade pip

      - name: Install prerequistes for testing
        run: |
          python -m pip install tox tox-gh

      - name: Prepare Tox
        run: |
          tox run -v --notest --skip-missing-interpreters false
        env:
          TOX_GH_MAJOR_MINOR: ${{ matrix.python }}

      - name: Run Tox
        run: |
          tox run --skip-pkg-install
        env:
          TOX_GH_MAJOR_MINOR: ${{ matrix.python }}

      - name: Rename coverage file
        run: |
          mv .coverage .coverage.${{ matrix.python }}

      - name: Upload coverage file
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
        with:
          name: coverage-${{ matrix.python }}
          path: .coverage.*
          include-hidden-files: true
          retention-days: 1

  coverage-report:
    name: Report Coverage
    runs-on: ubuntu-latest
    needs:
      - tests

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8

      - name: Set up Python 3.11
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065
        with:
          python-version: 3.11

      - name: Install coverage
        run: |
          pip install -U pip
          pip install coverage

      - name: Download coverage files
        uses: actions/download-artifact@634f93cb2916e3fdff6788551b99b062d0335ce0
        with:
          pattern: coverage-*
          merge-multiple: true

      - name: Combine coverage files
        run: |
          coverage combine

      - name: Report coverage
        run: |
          coverage report

  linting:
    name: Run MyPy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8

      - name: Set up Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065
        with:
          python-version: 3.11

      - name: Prepare pip
        run: |
          python -m pip install --upgrade pip

      - name: Install prerequistes for testing
        run: |
          python -m pip install .[test]

      - name: Run MyPy
        run: |
          mypy --exclude build .
