# vim: et

on:
  push:

jobs:
  common:
    uses: ./.github/workflows/common.yml

  publish-test:
    name: Publish pushes to PyPi's test instance
    if: github.event_name == 'push'
    needs:
      - common
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8

      - name: Set up Python
        uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c
        with:
          python-version: 3.11

      - name: Prepare pip and install build
        run: |
          python -m pip install --upgrade pip
          python -m pip install build

      - name: Make the version number unique
        run: |
          python update-version-for-test-push.py

      - name: Build source and wheel distributions
        run: |
          python -m build .

      - name: Publish pushes to PyPI test
        uses: pypa/gh-action-pypi-publish@76f52bc884231f62b9a034ebfe128415bbaabdfc
        with:
          repository-url: https://test.pypi.org/legacy/

  publish-prod:
    name: Publish tags to PyPi production
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    needs: common
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8

      - name: Set up Python
        uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c
        with:
          python-version: 3.11

      - name: Prepare pip and install build
        run: |
          python -m pip install --upgrade pip
          python -m pip install build

      - name: Build source and wheel distributions
        run: |
          python -m build .

      - name: Publish tags to PyPI production
        uses: pypa/gh-action-pypi-publish@76f52bc884231f62b9a034ebfe128415bbaabdfc
