# vim: et

on:
  pull_request:

jobs:
  common:
    uses: ./.github/workflows/common.yml

  bandit:
    name: Run Bandit
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3

      - name: Set up Python
        uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c
        with:
          python-version: 3.11

      - name: Prepare pip
        run: |
          python -m pip install --upgrade pip

      - name: Install prerequistes for testing
        run: |
          python -m pip install bandit[toml]

      - name: Run Bandit
        run: |
          bandit --configfile pyproject.toml --recursive src tests
