# vim: et

on:
  pull_request:

jobs:
  common:
    uses: ./.github/workflows/common.yml

  bandit:
    name: Run Bandit
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8

      - name: Set up Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065
        with:
          python-version: 3.11

      - name: Prepare pip
        run: |
          python -m pip install --upgrade pip

      - name: Install prerequistes for testing
        run: |
          python -m pip install bandit[toml]

      - name: Run Bandit
        run: |
          bandit --configfile pyproject.toml --recursive src tests
