# vim: et

on:
  pull_request:

jobs:
  tests:
    name: Run Tox & PyTest
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python:
          - "3.11"
          - "3.12"
          - "3.13"

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065
        with:
          python-version: ${{ matrix.python }}

      - name: Prepare pip
        run: |
          python -m pip install --upgrade pip

      - name: Install prerequistes for testing
        run: |
          python -m pip install tox tox-gh

      - name: Prepare Tox
        run: |
          tox run -v --notest --skip-missing-interpreters false
        env:
          TOX_GH_MAJOR_MINOR: ${{ matrix.python }}

      - name: Run Tox
        run: |
          tox run --skip-pkg-install
        env:
          TOX_GH_MAJOR_MINOR: ${{ matrix.python }}

  linting:
    name: Run MyPy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8

      - name: Set up Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065
        with:
          python-version: 3.11

      - name: Prepare pip
        run: |
          python -m pip install --upgrade pip

      - name: Install prerequistes for testing
        run: |
          python -m pip install .[test]

      - name: Run MyPy
        run: |
          mypy .

  bandit:
    name: Run Bandit
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8

      - name: Set up Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065
        with:
          python-version: 3.11

      - name: Prepare pip
        run: |
          python -m pip install --upgrade pip

      - name: Install prerequistes for testing
        run: |
          python -m pip install bandit[toml]

      - name: Run Bandit
        run: |
          bandit --configfile pyproject.toml --recursive src tests
